config/routes.rb
Txlogic::Application.routes.draw do
  devise_for :users
  
  resources :alerts do
    member do
      get 'accept'
      get 'stop'
    end
  end
  post 'launch/(:id)' => "alerts#create", :as => :launch, :constraints => { :protocol => 'https' }

  resources :a, :controller => :alert_deliveries, :only => :show

  resources :process_definitions, :as => 'processes' do
    member do
      get 'invoke'
      post 'pause'
      post 'resume'
    end
  end

  resources :replies do
    collection do
      post 'tropo'
      post 'mailgun'
    end
  end
  
  resources :members, :only => [ :index, :create, :destroy ]
  
  #root :to => "alerts#index"
  root :to => "pages#index"
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :customer
  belongs_to :process_definition
  has_many   :deliveries,  :class_name => 'AlertDelivery', :dependent => :destroy, :order => 'id DESC'
  belongs_to :resolved_by, :class_name => 'AlertDelivery'

  before_create :set_customer_from_process_definition

  validates_presence_of :process_definition_id
  
  default_scope order('id DESC')  
  scope :unresolved, :conditions => { :resolution => nil }
  
  cattr_reader :per_page
  @@per_page = 10
  
  def kickoff
    save! if new_record?
    
    return true if handled_locally?
    
    $alerter ||= Alerter.new
    
    $alerter.kickoff(process_definition.runnable_process,
      process_definition.time_zone,
      'alert_id' => id, 'alert_process_name' => process_definition.name,
      'subject' => subject, 'message' => message,
      'url' => URI.join(Settings.alerts.reply_base_url, "alerts/#{id}"),
      'tz' => process_definition.time_zone)
  end
  
  def running?
    !resolution && (updated_at > 30.minutes.ago)
  end
  
  def resolver
    read_attribute(:resolver) || (resolved_by && resolved_by.recipient)
  end
  
  def most_recent_delivery_workitem_id
    deliveries.find(:first, :conditions => [ 'workitem_id IS NOT NULL' ]).try(:workitem_id)
  end

  def accept(username)
    $alerter ||= Alerter.new
    
#    begin
      $alerter.cancel_process(most_recent_delivery_workitem_id)
#    rescue ArgumentError
#    end
    update_attribute(:resolution, 'Accepted')
    update_attribute(:resolver, username)
  end
  
  def cancel(username)
    $alerter ||= Alerter.new
    
#    begin
      $alerter.cancel_process(most_recent_delivery_workitem_id)
#    rescue ArgumentError
#    end
    update_attribute(:resolution, 'Ended')
    update_attribute(:resolver, username)
  end
  
  protected
  def handled_locally?
    if !process_definition.active
      self.resolution = 'Not sent (process paused)'
    elsif process_definition.filter_alert?(self)
      self.resolution = 'Not sent (subject filter)'
    else
      return false
    end

    save
    true
  end

  def set_customer_from_process_definition
    self.customer_id ||= process_definition.customer_id
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [ :create ]
    
  def index
    @process_definitions = current_customer.process_definitions.all

    @alerts = Alert.where(:process_definition_id => @process_definitions).paginate(:page => params[:page])
    @active_alerts = @alerts.map(&:running?).include?(true)
  
    respond_to do |format|
      format.html
      format.json do 
        render :json => @alerts.to_json(:only => [ :id, :subject, 
          :message, :created_at, :updated_at, :resolution ])
      end
    end
  end
  
  def show
    @alert = current_customer.alerts.includes(:deliveries).find(params[:id])
  end
  
  def create
    launch_alias = nil  
    message = ''
    
    @alert = Alert.new
    
    if params[:alert]
      @alert = Alert.new(params[:alert])
    elsif params[:recipient]
      launch_alias_matches = params[:recipient].match(/alert-(.*)@/)
      launch_alias = launch_alias_matches[1]
      @alert.message = params['body-plain']
    elsif params[:message]
      @alert.message = params[:message]
    elsif params[:payload]
      @alert.message = JSON.pretty_generate(JSON.parse(params[:payload]))
    end
    
    @alert.subject ||= params[:subject] || ''
    @alert.subject = @alert.subject[0..254]
  
    if !@alert.process_definition
      @alert.process_definition = ProcessDefinition.find_by_launch_alias(launch_alias || params[:id])
    end

    Rails.logger.info "Starting #{@alert.process_definition.inspect}"
    
    # move to callback
    success = @alert.kickoff
    
    if success && params[:alert]
      # human
      flash[:notice] = 'Alert invoked.'
      redirect_to alerts_path
    elsif success
      render(:status => 200, :nothing => true)
    else
      render(:status => 412, :nothing => true)
    end
  end
  
  def accept
    @alert = current_customer.alerts.unresolved.find(params[:id])
    
    @alert.accept(current_user.email)

    flash[:notice] = 'Alert accepted.'
    redirect_to alerts_path
  end

  def stop
    @alert = current_customer.alerts.unresolved.find(params[:id])
    
    @alert.cancel(current_user.email)
        
    flash[:notice] = 'Alert ended.'
    redirect_to alerts_path
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
  def email_alias_link(process_definition)
    email_alias = "alert-#{process_definition.launch_alias}@txlogic.mailgun.org"
    link_to 'Email alias', "mailto:#{email_alias}"
  end

  def http_alias_link(process_definition)
    link_to 'HTTP URL', launch_path(:id => process_definition.launch_alias)
  end
  
  def date_based_on_age(t)
    return unless t
    
    exact_time = t.strftime('%B %e, %l:%m %p %Z')
    relative_time = time_ago_in_words(t).sub('about ', '') + ' ago'
    
    if t > 1.day.ago
      content_tag(:span, relative_time, :title => exact_time)
    else
      content_tag(:span, exact_time, :title => relative_time)
    end
  end

  def format_recipient(recipient, short_format = true)
    if recipient =~ /@/ && short_format
      recipient.split('@').first
    elsif recipient =~ /^\+1/
      PhoneNumber.new(recipient).to_us_number('-')
    else
      recipient
    end
  end
  
  def format_delivery_recipient(delivery, short_format = true)
    "#{format_recipient(delivery.recipient, short_format)} (#{delivery.formatted_delivery_method})"
  end
end

app/views/alerts/_delivery_list.html.erb
<tr>
  <td>
    <%= format_delivery_recipient(delivery, false) %>
  </td>
  <td>
    <%= content_tag :span, distance_of_time_in_words(delivery.alert.created_at, delivery.created_at, true).sub('less than', '<'), :title => delivery.created_at.to_s %>
  </td>
  <td colspan="3">
    <%= delivery.silenced? ? 'Silenced' : delivery.reply %>
  </td>
</tr>

app/views/alerts/_form.html.erb
<fieldset>
  <%= f.hidden_field :process_definition_id %>
  
  <div class="clearfix">
    <%= f.label :subject %>
    <div class="input">
      <%= f.text_field :subject %>
      <span class="help-block">Example: Something's down</span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :message %>
    <div class="input">
      <%= f.text_area :message, :class => "span6", :style => 'height: 125px;' %>
      <span class="help-block">Example: www123 is toast.</span>
    </div>
  </div>
</fieldset>

<div class="actions span6">
  <button class="btn primary" type="submit">Invoke Alert</button> or
  <%= link_to "Cancel", alerts_path %>
</div>

app/views/alerts/_sidebar.html.erb
<p>Scriptable, easy, cheap alerting.</p>

<!--
<div class="block notice">
  <h3>What Can I Do?</h3>    
  <div class="content">
  
    <p>Have your existing monitoring system send alerts via many methods, to many people,
    based on time, type
    <ul style="margin-left: 20px;">
      <li>Define a process</li>
      <li>Point monitoring at it (email, HTTP)</li>
      <li>Get alerts: IM, email, SMS, phone call</li>
    </ul>

    <p>Get fancy:</p>
    <ul style="margin-left: 20px;">
      <li>Notify multiple people <%= link_to 'concurrently', 'http://ruote.rubyforge.org/exp/concurrence.html' %></li>
      <li>Decide based on time or day</li>
      <li>"Shut up for 10 minutes" reply</li>
      <li>Testing and troubleshooting</li>
    </ul>

    <p>Make it your own:
    <ul style="margin-left: 20px;">     
      <li>Conditionals on alert-related variables (it's an alerting syntax)</li>
      <li>Send SMSes to most of the world</li>
      <li>Use your own hostname</li>
    </ul>
  </div>
</div>
-->

<h3>Actions</h3>
<ul>
  <li><%= link_to 'Create Process', new_process_path %></li>
</ul>

app/views/alerts/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", alerts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_alert_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_alert_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Alert</h2>
    <div class="inner">
      <%= form_for @alert, :url => alert_path(@alert), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/alerts/index.html.erb
<% if @active_alerts %>
  <% content_for :head do %>
    <meta http-equiv="refresh" content="180">
  <% end %>
<% end %>

<h2>Alerts</h2>

<table class="zebra-striped span13">
  <thead>
    <tr>             
      <th class="span5">Subject</th>
      <th>Invoked</th>
      <th>Process</th>
      <th>Resolution</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%- if @alerts.empty? -%>
    <tr>
      <td>No alerts started yet.</td>
    </tr>
    <%- end -%>

    <% @alerts.each do |alert| -%>
      <tr>
        <td>
          <% if alert.subject.length > 29 %>
            <span title="<%= alert.subject %>"><%= alert.subject[0..28] %></span>
          <% else %>
            <%= alert.subject && alert.subject[0..28] %>
          <% end %>
        </td>
        <td>
          <%= date_based_on_age(alert.created_at) %>
        </td>
        <td>
          <%= link_to alert.process_definition.to_s[0..23], edit_process_path(alert.process_definition) %>
        </td>
        <% unless alert.running? %>
        <td>
          <%= alert.resolution %> <%= "(#{format_recipient(alert.resolver)})" if alert.resolver %>
        </td>
        <% end %>

        <td colspan="<%= alert.running? ? 2 : 1 %>">
          <% if alert.running? %>
            <%= link_to 'Accept', accept_alert_path(alert), :confirm => 'Accept alert, ending further notifications?' %> 
            | <%= link_to 'End', stop_alert_path(alert), :confirm => 'End alert without further notifications?' %> 
            | 
          <% end %>
          <%= link_to 'Details', alert_path(alert) %>  
        </td>
      </tr>        
    <% end -%>
  </tbody>
</table>
        
<div class="pagination span10">
  <%= will_paginate @alerts, :previous_label => '&laquo; Newer', :next_label => 'Older &raquo;', :inner_window => 1, :outer_window => 1 %>  
</div>

<hr class="span13">

<h2>Processes</h2>

<table class="zebra-striped span13">
  <thead>
    <tr>             
      <th class="span5">Name</th>
      <th>Invoke Via</th>
      <th>Created</th>
      <th>Invocations</th>
      <th>Actions</th>
    </tr>
  </thead>
  
  <tbody>
    <% @process_definitions.each do |p_d| -%>
    <tr>
      <td>
        <%= p_d.name %>
      </td>
      <td>
        <%= email_alias_link(p_d) %>,   
        <%= http_alias_link(p_d) %>
      </td>
      <td>
        <%= p_d.created_at.strftime('%B %e') %>
      </td>
      <td>
        <%= p_d.alerts.count %>
      </td>

      <td class="last">
        <% if p_d.active? %>
          <%= link_to("Pause", pause_process_path(p_d), :method => :post, :confirm => 'This process will not send any alerts while paused. Are you sure?') %>
        <% else %>
          <%= link_to("Resume", resume_process_path(p_d), :method => :post, :confirm => 'Start sending alerts again?') %>
        <% end %> |
        <%= link_to 'Test', invoke_process_path(p_d), :method => :get %> |
        <%= link_to 'Edit', edit_process_path(p_d) %> |
        <%= link_to 'Delete', process_path(p_d), :method => :delete, :confirm => "Really delete #{p_d.name}?" %>
      </td>
    </tr>          
    <% end -%>
  </tbody>
</table>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/alerts/show.html.erb
<% if @alert.running? %>
  <% content_for :head do %>
    <meta http-equiv="refresh" content="180">
  <% end %>
<% end %>

<h2 class="span12">Alert: <%= @alert.subject[0..60] %></h2>

<% if @alert.running? %>
  <%= render 'alert_delivery/choices', :alert => @alert %>
<% end %>

<table style="margin-top: 25px;">
  <tbody>
    <tr>
      <th>Process</th>
      <td><%= link_to @alert.process_definition, process_path(@alert.process_definition) %></td>
    </tr>
    
    <tr>
      <th>Invoked</th>
      <td><%= @alert.created_at %> (<%= time_ago_in_words(@alert.created_at) %> ago)</td>
    </tr>
    
    <tr>
      <th>Resolution</th>
      <td><%= @alert.resolution %> <%= "(#{format_recipient(@alert.resolver)})" if @alert.resolver %></td>
    </tr>

    <tr>
      <th>Subject</th>
      <td><%= @alert.subject %></td>
    </tr>

    <tr>
      <th>Message</th>
      <td>
        <pre style="white-space: pre-wrap; white-space: -moz-pre-wrap !important; white-space: -pre-wrap; white-space: -o-pre-wrap; word-wrap: break-word;"><%= @alert.message %></pre>
      </td>
    </tr>
  </tbody>
</table>


<h3>Notifications</h3>
  
<table class="zebra-striped span11">
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Elapsed After Invocation</th>
      <th>Reply</th>
    </tr>
  </thead>
  
  <tbody>
    <%= render :partial => 'alerts/delivery_list', :collection => @alert.deliveries, :as => :delivery %>
  </tbody>
</table>

<% content_for :sidebar, render(:partial => 'alerts/sidebar') -%>