config/routes.rb
Txlogic::Application.routes.draw do
  devise_for :users
  
  resources :alerts do
    member do
      get 'accept'
      get 'stop'
    end
  end
  post 'launch/(:id)' => "alerts#create", :as => :launch, :constraints => { :protocol => 'https' }

  resources :a, :controller => :alert_deliveries, :only => :show

  resources :process_definitions, :as => 'processes' do
    member do
      get 'invoke'
      post 'pause'
      post 'resume'
    end
  end

  resources :replies do
    collection do
      post 'tropo'
      post 'mailgun'
    end
  end
  
  resources :members, :only => [ :index, :create, :destroy ]
  
  #root :to => "alerts#index"
  root :to => "pages#index"
end

app/models/process_definition.rb
class ProcessDefinition < ActiveRecord::Base
  belongs_to :customer
  has_many :alerts, :dependent => :destroy

  validates_presence_of :customer_id  
  validates_presence_of :launch_alias
  validates_presence_of :definition
  validates_uniqueness_of :launch_alias
  
  default_scope order(:name)
  attr_protected :launch_alias, :definition
  
  before_validation :set_launch_alias, :on => :create
  validate :valid_syntax
  
  def to_s
    name
  end
  
  def time_zone
    read_attribute(:time_zone) || 'UTC'
  end

  def process_markup
    self.definition.sub(/^Ruote\./, '') if self.definition.present?
  end
  def process_markup=(new_markup)
    self.definition = "Ruote." + new_markup.strip
  end
  
  def runnable_process
    Ruote::Reader.read(definition)
  end
  
  def filter_alert?(alert)
    self.subject_filter.present? && alert.subject.present? && Regexp.new(self.subject_filter).match(alert.subject)
  end

  protected
  def set_launch_alias
    self.launch_alias = SecureRandom.hex(8)
  end
  
  def valid_syntax
    begin
      parsed = runnable_process
    rescue
      errors.add(:base, "Definition is invalid or incomplete")
      return false
    end
    
    if parsed.is_a?(Array)
      return true
    end
    
    errors.add(:base, "Definition is invalid or incomplete")    
    return false
  end  
end

app/controllers/process_definitions_controller.rb
class ProcessDefinitionsController < ApplicationController
  def show
    redirect_to edit_process_path(current_customer.process_definitions.find(params[:id]))
  end
  
  def new
    @process_definition = current_customer.process_definitions.build
  end
  
  def create
    @process_definition = current_customer.process_definitions.build(params[:process_definition])
    
    if @process_definition.save
      # this should be flash.now but web-app-theme doesn't honor it
      flash[:notice] = verifying? ? 'Valid. Saved.' : 'Created.'
          
      respond_to do |format|
        format.html { redirect_to(verifying? ? edit_process_path(@process_definition) : alerts_path) }
      end
    else
      flash[:error] = "Sorry, this process isn't valid or is incomplete. Trying to accomplish a workflow? Send us a note."
      render :new
    end
  end
  
  def edit
    @process_definition = current_customer.process_definitions.find(params[:id])
  end
  
  def update
    @process_definition = current_customer.process_definitions.find(params[:id])
    
    if @process_definition.update_attributes(params[:process_definition])
      # this should be flash.now but web-app-theme doesn't honor it
      flash[:notice] = verifying? ? 'Valid. Updated.' : 'Updated.'

      respond_to do |format|
        format.html { redirect_to(verifying? ? edit_process_path(@process_definition) : alerts_path) }
      end
    else
      flash[:error] = "Sorry, this process isn't valid or is incomplete. Trying to accomplish a workflow? Send us a note."
      render :edit
    end
  end
  
  def destroy
    respond_to do |format|
      if current_customer.process_definitions.find(params[:id]).destroy
        format.html do 
          flash[:notice] = 'Process deleted.'
          redirect_to alerts_path
        end
      else
        format.html do
          flash[:error] = 'Sorry, an error occurred while deleting this process. Please contact support.'
          redirect_to alerts_path
        end          
      end
    end    
  end
  
  def invoke
    @process_definition = current_customer.process_definitions.find(params[:id])
    @alert = @process_definition.alerts.build
  end
  
  def pause
    @process_definition = current_customer.process_definitions.find(params[:id])
    @process_definition.update_attribute(:active, false)
    
    redirect_to alerts_path
  end
  
  def resume
    @process_definition = current_customer.process_definitions.find(params[:id])
    @process_definition.update_attribute(:active, true)
    
    redirect_to alerts_path
  end
  
  private
  def verifying?
    params[:verify].present?
  end
end

app/helpers/process_definitions_helper.rb
module ProcessDefinitionsHelper
  def default_markup
    """
process_definition do
  concurrence :timeout => '2m' do
    participant 'im alfonso',  :recipient => 'alfonso@example.com', :using => 'jabber'
    participant 'im sally', :recipient => 'sally79', :using => 'yahoo'
  end

  participant 'email ops', :recipient => 'ops@example.com', :timeout => '5m'

  concurrence :timeout => '5m' do
    participant 'sms alfonso', :recipient => '2065551234'
    participant 'call ops on-call phone', :recipient => '5125553210'
  end
  
  participant 'call developer', :recipient => '4155556789',
    :timeout => '2m', :if => '${hour} > 9 && ${hour} < 18'
  participant 'call ceo', :recipient => '2125554400', :if => '${weekday} && ${daytime}'
end
"""
  end
end

app/views/process_definitions/_form.html.erb
<fieldset>
  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>
      <span class="help-block">Ex: Production server escalation</span>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :process_markup, "Definition" %> 
    <div class="input">
      <%= f.text_area :process_markup, :value => @process_definition.process_markup || default_markup, :style => 'font-family: Courier, monospace;', :class => 'span11' %>
      <span class="help-block"><%= link_to('Docs', 'https://github.com/troy/txlogic', :target => '_blank') %>. Whitespace doesn't matter. And yes, this is Ruby syntax. Mostly.</span>    
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :subject_filter, 'Subject filter (optional)', :class => 'optional' %>
    <div class="input span7">
      <%= f.text_field :subject_filter, :class => 'span6' %>
      <span class="help-block">Don't want alerts for "back up" notices or test systems? Filter them. Example: Back to|UP alert|staging</span>    
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :time_zone, "Your time zone" %>
    <div class="input">
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {}, :class => 'span6' %>
      <span class="help-block">Your alert will be passed the time in this zone.</span>
    </div>
  </div>
</fieldset>

<div class="actions span11">
  <button class="btn primary" type="submit">Verify & Save</button> or
  <button class="btn" type="submit" name="verify" value="1">Verify, Save, & Keep Editing</button>
</div>

app/views/process_definitions/_sidebar.html.erb
<p>Define your ideal escalation process.</p>
    
<p>Send an IM to multiple engineers, and if no one replies 
to acknowledge the issue, proceed to email, SMS, and phone calls.</p>

<p>Notify concurrently, use date and time, pass in variables,
introduce loops, and more.</p>

<% unless @process_definition.new_record? %>
  <h3><%= @process_definition %></h3>
  <ul>
    <li><%= link_to "Edit", edit_process_path(@process_definition) %></li>
    <li><%= link_to "Invoke", invoke_process_path(@process_definition) %></li>
  </ul>

  <h3>Help</h3>
  <ul>
    <li><%= link_to "Docs", "https://github.com/troy/txlogic" %></li>
  </ul>
<% end %>
  
<!--
<div class="block">
  <h3>How Do I...</h3>
  <ul class="navigation">
    <li><a href="#">Send IM, email, SMS, or call</a></li>
    <li><a href="#">Notify multiple people at once</a></li>
    <li><a href="#">Use date and time</a></li>
  </ul>
</div>

<div class="block">
  <h3>Advanced</h3>
  <ul class="navigation">
    <li><a href="#">Define alert-specific variables</a></li>
    <li><a href="#">Use loops and conditionals</a></li>
    <li><a href="#">Host definition on any Web server</a></li>
  </ul>
</div>
-->

app/views/process_definitions/edit.html.erb
<div class="block">
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Process</h2>
    <div class="inner">
      <%= form_for @process_definition, :url => process_path(@process_definition), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => { :f => f } %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/process_definitions/invoke.html.erb
<div class="block">
  <div class="content">            
    <h2 class="title">Invoke Process: <%= @process_definition.name %></h2>
    <div class="inner">
      <%= form_for :alert, :url => alerts_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "alerts/form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/process_definitions/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "Define New Process")}", new_process_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%> Process</h2>
    <div class="inner">
      <%= form_for :process_definition, :url => processes_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/process_definitions/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li><%= link_to "#{t("web-app-theme.new", :default => "New Process")}", new_process_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Test")}", invoke_process_path(@process_definition) %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.process_definition.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @process_definition.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.process_definition.launch_alias", :default => t("activerecord.labels.launch_alias", :default => "Alias")) %>:</b>
          <%= @process_definition.launch_alias %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.process_definition.process_markup", :default => t("activerecord.labels.process_markup", :default => "Definition")) %>:</b>
          <%= @process_definition.process_markup %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_process_definition_path(@process_definition), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), process_definition_path(@process_definition), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>