config/routes.rb
Txlogic::Application.routes.draw do
  devise_for :users
  
  resources :alerts do
    member do
      get 'accept'
      get 'stop'
    end
  end
  post 'launch/(:id)' => "alerts#create", :as => :launch, :constraints => { :protocol => 'https' }

  resources :a, :controller => :alert_deliveries, :only => :show

  resources :process_definitions, :as => 'processes' do
    member do
      get 'invoke'
      post 'pause'
      post 'resume'
    end
  end

  resources :replies do
    collection do
      post 'tropo'
      post 'mailgun'
    end
  end
  
  resources :members, :only => [ :index, :create, :destroy ]
  
  #root :to => "alerts#index"
  root :to => "pages#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transmit Logic</title>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <link href='https://fonts.googleapis.com/css?family=Monofett|Josefin+Sans:600italic|Terminal+Dosis+Light' rel='stylesheet' type='text/css'>
  <%= css3buttons_stylesheets :include_reset => false %>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
  
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

<div class="topbar">
  <div class="topbar-inner">
    <div class="container">
      <a href="/" class="brand" style="font-family: Terminal Dosis Light; font-size: 24px; color: orange; letter-spacing: 0.1em; margin-top: -2px;">&lt; <span style="letter-spacing: 0.13em; margin-right: 0.20em;">tx logic</span>&gt;</a>
      <ul class="nav secondary-nav">
        <li><%= link_to 'Members', members_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, :method => 'delete', :class => 'logout' %></li>          
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid" style="padding-top: 60px;">
  <div class="sidebar" style="padding-top: 60px;">
    <div class="well">
      <%= yield :sidebar %>
    </div>
  </div>

  <div class="content" style="width: 700px;">
    <div class="row">
      <div class="span6">
        <div class="flash">
          <% flash.each do |type, message| -%>
            <div class="message <%= type %>">
              <p><%= message %></p>
            </div>
          <% end -%>
        </div>
  
        <%= yield %>
      </div>
    </div>
  </div>
  
  <footer>
    <div class="block">
      <%= link_to 'Transmit Logic', 'https://github.com/troy/txlogic/' %>
    </div>      
  </footer>
    
</div>

</body>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Transmit Logic</title>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <link href='https://fonts.googleapis.com/css?family=Monofett|Josefin+Sans:600italic|Terminal+Dosis+Light' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
</head>

<body>
<div class="topbar">
  <div class="topbar-inner">
    <div class="container">
      <a href="/" class="brand" style="font-family: Terminal Dosis Light; font-size: 24px; color: orange; letter-spacing: 0.1em; margin-top: -2px;">&lt; <span style="letter-spacing: 0.13em; margin-right: 0.20em;">tx logic</span>&gt;</a>
      <ul class="nav secondary-nav">
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid" style="padding-top: 60px;">
  <div class="content" style="width: 700px;">

    <div class="flash">
      <% flash.each do |type, message| -%>
        <div class="message <%= type %>">
          <p><%= message %></p>
        </div>
      <% end -%>
    </div>
    
    <%= yield %>            
  </div>  
</div>
</body>
</html>