config/routes.rb
Txlogic::Application.routes.draw do
  devise_for :users
  
  resources :alerts do
    member do
      get 'accept'
      get 'stop'
    end
  end
  post 'launch/(:id)' => "alerts#create", :as => :launch, :constraints => { :protocol => 'https' }

  resources :a, :controller => :alert_deliveries, :only => :show

  resources :process_definitions, :as => 'processes' do
    member do
      get 'invoke'
      post 'pause'
      post 'resume'
    end
  end

  resources :replies do
    collection do
      post 'tropo'
      post 'mailgun'
    end
  end
  
  resources :members, :only => [ :index, :create, :destroy ]
  
  #root :to => "alerts#index"
  root :to => "pages#index"
end

app/controllers/members_controller.rb
require 'securerandom'

class MembersController < ApplicationController
  def index
    @users = current_customer.users.all
    
    @user = current_customer.users.build
  end
  
  def create
    pw = SecureRandom.hex(8)
    @user = current_customer.users.build :email => params[:user][:email], 
      :password => pw, :password_confirmation => pw,
      :invitation_code => User::INVITATION_CODE
    # does not do mass assignment
    @user.confirmed_at = Time.now

    if @user.save && @user.send_member_invitation
      flash[:info] = "Invitation email sent."
    else
      flash[:error] = "Sorry, an error occurred."
    end

    respond_to do |format|
      format.html { redirect_to members_path }
    end 
  end
  
  def destroy
    @user = current_customer.users.find params[:id]

    if @user != current_user && @user.destroy
      flash[:info] = "User removed."
    elsif @user == current_user
      flash[:error] = "Can't delete yourself, even on a bad day."
    else
      flash[:error] = "Sorry, an error occurred."
    end

    respond_to do |format|
      format.html { redirect_to members_path }
    end
  end
end

app/views/members/_sidebar.html.erb
<p>Invite others to manage your alerts.</p>

app/views/members/index.html.erb
<h2>Users</h2>

<table class="zebra-striped span8">
  <thead>
    <tr>
      <th>Email</th>
      <th>Added</th>
      <th>Actions</th>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| -%>
    <tr>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= date_based_on_age(user.created_at) %>
      </td>
      <td>
        <% unless user == current_user %>
          <%= link_to "Remove", member_path(user), :method => "delete", :confirm => 'Remove Web access for this user?' %>
        <% end %>
      </td>
    </tr>
    <% end -%>
  </tbody>
</table>

<hr>
<h2>Add User</h2>

<%= form_for @user, :url => members_path, :method => 'post' do |f| %>
  <fieldset>
    <div class="clearfix">
      <%= f.label :email, 'Email address' %>
      <div class="input">
        <%= f.text_field :email %>
      </div>
    </div>
  </fieldset>

  <div class="actions span5">
    <button class="btn primary" type="submit">Invite</button>
  </div>
<% end %>

<% content_for :sidebar, render(:partial => 'sidebar') -%>